"""Item Price List"""

import json
import requests

ENCHANTS = {
    "ENCHANTMENT_BIG_BRAIN": 5,
    "ENCHANTMENT_BANE_OF_ARTHROPODS": 7,
    "ENCHANTMENT_BLAST_PROTECTION": 7,
    "ENCHANTMENT_CHAMPION": 1,
    "ENCHANTMENT_CLEAVE": 6,
    "ENCHANTMENT_CHANCE": 5,
    "ENCHANTMENT_CRITICAL": 7,
    "ENCHANTMENT_CUBISM": 6,
    "ENCHANTMENT_DIVINE_GIFT": 3,
    "ENCHANTMENT_DRAGON_HUNTER": 5,
    "ENCHANTMENT_DRAGON_TRACER": 5,
    "ENCHANTMENT_ENDER_SLAYER": 7,
    "ENCHANTMENT_EXECUTE": 6,
    "ENCHANTMENT_EXPERIENCE": 5,
    "ENCHANTMENT_FLAME": 2,
    "ENCHANTMENT_FIRE_ASPECT": 3,
    "ENCHANTMENT_FIRST_STRIKE": 5,
    "ENCHANTMENT_GIANT_KILLER": 7,
    "ENCHANTMENT_IMPALING": 3,
    "ENCHANTMENT_INFINITE_QUIVER": 10,
    "ENCHANTMENT_KNOCKBACK": 2,
    "ENCHANTMENT_LETHALITY": 6,
    "ENCHANTMENT_LIFE_STEAL": 5,
    "ENCHANTMENT_LOOTING": 5,
    "ENCHANTMENT_LUCK": 7,
    "ENCHANTMENT_MANA_STEAL": 3,
    "ENCHANTMENT_OVERLOAD": 5,
    "ENCHANTMENT_PIERCING": 1,
    "ENCHANTMENT_POWER": 7,
    "ENCHANTMENT_PUNCH": 2,
    "ENCHANTMENT_PROSECUTE": 6,
    "ENCHANTMENT_SCAVENGER": 5,
    "ENCHANTMENT_SHARPNESS": 7,
    "ENCHANTMENT_SMITE": 7,
    "ENCHANTMENT_SMOLDERING": 5,
    "ENCHANTMENT_SNIPE": 4,
    "ENCHANTMENT_SYPHON": 5,
    "ENCHANTMENT_TABASCO": 3,
    "ENCHANTMENT_THUNDERBOLT": 6,
    "ENCHANTMENT_THUNDERLORD": 7,
    "ENCHANTMENT_TITAN_KILLER": 7,
    "ENCHANTMENT_TRIPLE_STRIKE": 5,
    "ENCHANTMENT_VAMPIRISM": 6,
    "ENCHANTMENT_VENOMOUS": 6,
    "ENCHANTMENT_VICIOUS": 5,
    "ENCHANTMENT_FEROCIOUS_MANA": 10,
    "ENCHANTMENT_FIRE_PROTECTION": 7,
    "ENCHANTMENT_GROWTH": 7,
    "ENCHANTMENT_HARDENED_MANA": 10,
    "ENCHANTMENT_HECATOMB": 1,
    "ENCHANTMENT_MANA_VAMPIRE": 10,
    "ENCHANTMENT_PROJECTILE_PROTECTION": 7,
    "ENCHANTMENT_PROTECTION": 7,
    "ENCHANTMENT_REJUVENATE": 5,
    "ENCHANTMENT_RESPITE": 5,
    "ENCHANTMENT_STRONG_MANA": 10,
    "ENCHANTMENT_TRUE_PROTECTION": 1,
    "ENCHANTMENT_COUNTER_STRIKE": 5,
    "ENCHANTMENT_SMARTY_PANTS": 5,
    "ENCHANTMENT_FEATHER_FALLING": 10,
    "ENCHANTMENT_SUGAR_RUSH": 3,
    "ENCHANTMENT_COMPACT": 1,
    "ENCHANTMENT_FORTUNE": 4,
    "ENCHANTMENT_PRISTINE": 5,
    "ENCHANTMENT_CULTIVATING": 1,
    "ENCHANTMENT_DEDICATION": 4,
    "ENCHANTMENT_DELICATE": 5,
    "ENCHANTMENT_HARVESTING": 6,
    "ENCHANTMENT_REPLENISH": 1,
    "ENCHANTMENT_TURBO_CACTI": 5,
    "ENCHANTMENT_TURBO_CANE": 5,
    "ENCHANTMENT_TURBO_CARROT": 5,
    "ENCHANTMENT_TURBO_MUSHROOMS": 5,
    "ENCHANTMENT_TURBO_POTATO": 5,
    "ENCHANTMENT_TURBO-WARTS": 5,
    "ENCHANTMENT_TURBO_WHEAT": 5,
    "ENCHANTMENT_TURBO_COCO": 5,
    "ENCHANTMENT_TURBO_MELON": 5,
    "ENCHANTMENT_TURBO_PUMPKIN": 5,
    "ENCHANTMENT_SUNDER": 5,
    "ENCHANTMENT_ANGLER": 6,
    "ENCHANTMENT_BLESSING": 6,
    "ENCHANTMENT_CASTER": 6,
    "ENCHANTMENT_CHARM": 5,
    "ENCHANTMENT_CORRUPTION": 5,
    "ENCHANTMENT_EXPERTISE": 1,
    "ENCHANTMENT_FRAIL": 6,
    "ENCHANTMENT_LUCK_OF_THE_SEA": 6,
    "ENCHANTMENT_LURE": 6,
    "ENCHANTMENT_MAGNET": 6,
    "ENCHANTMENT_PISCARY": 6,
    "ENCHANTMENT_SPIKED_HOOK": 6,
    "ENCHANTMENT_CAYENNE": 5,
    "ENCHANTMENT_GREEN_THUMB": 5,
    "ENCHANTMENT_PROSPERITY": 5
}

ULT_ENCHANTS = {
    "ENCHANTMENT_ULTIMATE_BANK": 5,
    "ENCHANTMENT_ULTIMATE_BOBBIN_TIME": 5,
    "ENCHANTMENT_ULTIMATE_CHIMERA": 5,
    "ENCHANTMENT_ULTIMATE_COMBO": 5,
    "ENCHANTMENT_ULTIMATE_DUPLEX": 5,
    "ENCHANTMENT_ULTIMATE_FATAL_TEMPO": 5,
    "ENCHANTMENT_ULTIMATE_FLASH": 5,
    "ENCHANTMENT_ULTIMATE_HABANERO_TACTICS": 5,
    "ENCHANTMENT_ULTIMATE_INFERNO": 5,
    "ENCHANTMENT_ULTIMATE_LAST_STAND": 5,
    "ENCHANTMENT_ULTIMATE_LEGION": 5,
    "ENCHANTMENT_ULTIMATE_NO_PAIN_NO_GAIN": 5,
    "ENCHANTMENT_ULTIMATE_ONE_FOR_ALL": 1,
    "ENCHANTMENT_ULTIMATE_REND": 5,
    "ENCHANTMENT_ULTIMATE_SOUL_EATER": 5,
    "ENCHANTMENT_ULTIMATE_SWARM": 5,
    "ENCHANTMENT_ULTIMATE_WISE": 5,
    "ENCHANTMENT_ULTIMATE_WISDOM": 5
}

ITEM_UPGRADES = [
    'RECOMBOBULATOR_3000',
    'HOT_POTATO_BOOK',
    'FUMING_POTATO_BOOK',
]   

ENCHANTS_PRICE = {}
ULT_ENCHANTS_PRICE = {}
ITEM_UPGRADES_PRICE = {}

ITEM_WORTH = 0.8
AUCTION_SITE = 'https://api.hypixel.net/skyblock/auctions'
BAZAAR_SITE = 'https://api.hypixel.net/skyblock/bazaar'

def loadCurrentPrice():
    r = requests.get(BAZAAR_SITE)
    bz_data = json.loads(r.text)
    for ekey, evalue in ENCHANTS.items():
        for i in range(evalue):
            try:
                ENCHANTS_PRICE.update({f"{ekey}_{i+1}" : round(bz_data['products'][f"{ekey}_{i+1}"]['quick_status']['buyPrice'])})
            except:
                ENCHANTS_PRICE.update({f"{ekey}_{i+1}" : 0})
    for ukey, uvalue in ULT_ENCHANTS.items():
        for j in range(uvalue):
            try:
                ULT_ENCHANTS_PRICE.update({f"{ukey}_{j+1}" : round(bz_data['products'][f"{ukey}_{j+1}"]['quick_status']['buyPrice'])})
            except:
                ULT_ENCHANTS_PRICE.update({f"{ukey}_{j+1}" : 0})
    for k in ITEM_UPGRADES:
        ITEM_UPGRADES_PRICE.update({k : round(bz_data['products'][k]['quick_status']['buyPrice'])})
    
loadCurrentPrice()

with open ('enchantp.txt', 'w') as file:
    file.write(json.dumps(ENCHANTS_PRICE, indent = 4))
        
with open ('ultenchantp.txt', 'w') as file:
    file.write(json.dumps(ULT_ENCHANTS_PRICE, indent = 4))

with open ('itemp.txt', 'w') as file:
    file.write(json.dumps(ITEM_UPGRADES_PRICE, indent = 4))